# Generated by Django 5.2.8 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=12)),
            ],
        ),
    ]
