# Generated by Django 5.2.8 on 2026-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Proof of payment (image or PDF)', null=True, upload_to='payment_receipts/'),
        ),
    ]
