# Generated by Django 5.2.8 on 2026-03-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_full',
        ),
    ]
