# Generated by Django 5.2.6 on 2026-03-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostel_price'),
        ('hostels', '0002_remove_block_capacity_remove_room_is_full'),
    ]

    operations = [
    ]
