# Generated by Django 5.2.6 on 2026-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_hostel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, help_text='Hostel banner image', null=True, upload_to='hostel_images/'),
        ),
    ]
